name: iOS Build & Submit

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build iOS and Submit to TestFlight
    runs-on: macos-15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.1"

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo and EAS CLI
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Run prebuild
        run: npx expo prebuild --platform ios --clean

      - name: Resolve SPM Dependencies
        run: cd ios && xcodebuild -resolvePackageDependencies -workspace NGNflow.xcworkspace -scheme NGNflow
